title: Gaurav Tiwari
subtitle: An Enthusiastic Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
 This site is to know about Gaurav Tiwari. You can find various articles on the basis of Literature,Travel,
 Politics and Technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://peacefulheart12.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: gaurav.JPG
disqus_shortname: gauravtiwari-1  #for comments using disqus
author: Gaurav
author_bio: I am a software engineer. Likely,softwares are intengible heart is also intengible. So,I belive in love and software.A dream doesnot become reality through magic;It takes enthusiasm ,determination and hard work.I believe in hardwork and loyality.I am a technical field's person however, I believe in communicating and building relationships among people.I am also familiar with corporate culture and working environment.
author_email: "gauravtiwari8642@gmail.com"
author_location: Nepal
author_website_url: "https://gauravtiwari.com.np"

# social links
github_username:  peacefulheart12
facebook_username: gaurav.tiwari.54922169
linkedin_username: gaurav-tiwari-555b7b139
instagram_username: gaurav_tiwari666